### ISSUE TITLE
System.ObjectDisposedException

### ISSUE THREAD

**Issue by imadhajjchahine** [MonetDB/MonetDB-.Net#2]
Hi,

After being using this library in our dev environments for a while now, I am starting seeing some crash reports in IIS logs.
Referring https://github.com/MonetDB/MonetDB-.Net/issues/1#issuecomment-779254653
 

Application: iisexpress.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at System.Net.Sockets.NetworkStream.Write(Byte[], Int32, Int32)
   at System.IO.BufferedStream.Flush()
   at MonetDb.Mapi.Helpers.Mapi.Stream.WriteNextBlock(Boolean)
   at System.IO.StreamWriter.Flush(Boolean, Boolean)
   at System.IO.StreamWriter.Dispose(Boolean)
   at System.IO.StreamWriter.Close()
   at MonetDb.Mapi.Helpers.Mapi.Socket.Dispose()
   at MonetDb.Mapi.Helpers.ConnectionPool.Dispose()
   at MonetDb.Mapi.Helpers.ConnectionPool.Finalize()

and

An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/2/ROOT

Process ID: 35996

Exception: System.ObjectDisposedException

Message: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.

StackTrace:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Flush()
   at MonetDb.Mapi.Helpers.Mapi.Stream.WriteNextBlock(Boolean last)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at MonetDb.Mapi.Helpers.Mapi.Socket.Dispose()
   at MonetDb.Mapi.Helpers.ConnectionPool.Dispose()
   at MonetDb.Mapi.Helpers.ConnectionPool.Finalize()

**Comment by MitchellWeg** [comment]
Sorry for the late reply.

Do you have some code for me to debug, or is it the same as the previous issue?

**Comment by MitchellWeg** [comment]
I've created a connection with a poolmaximum of 2, and opened 3 connections. It correctly threw the _PoolMaximumExceeded_ exception. 

On which version of this library are you? Did you clone this package from GitHub or did you get it from NuGet? The version on NuGet is actually older. We are currently resolving that issue.
